### ISSUE TITLE
Fix text ghosting bug

### ISSUE THREAD

**Issue by stursby** [stursby/tiny-clock#6]
After building the app and letting it run for a few minutes, faint text shadows appear behind the time.

![image](https://cloud.githubusercontent.com/assets/527849/24765268/cc42be68-1abc-11e7-8cae-d697233d8eda.png)

It does go away after you click to focus the window again.

![image](https://cloud.githubusercontent.com/assets/527849/24765282/dc17e912-1abc-11e7-8342-58b29a5496c2.png)

*Also, this does not happen in Dev, only after building.*

**Comment by davidpett** [comment]
not seeing this anymore with `focusable: false` https://github.com/stursby/tiny-clock/pull/9
